imports:
    - { resource: 'issue_status_flow/steps.yml' }
    - { resource: 'issue_status_flow/attributes.yml' }
    - { resource: 'issue_status_flow/transitions.yml' }
    - { resource: 'issue_status_flow/transition_definitions.yml' }

workflows:
    issue_status_flow:
        label: 'Issue Status Flow'
        entity: Anyt\BugTrackerBundle\Entity\Issue
        entity_attribute: issue
        start_step: open
